- hosts: devel
  user: root

  tasks:
    - name: Generate a new public key
      user:
        name: root
        generate_ssh_key: yes
        ssh_key_bits: 2048

    - name: Add a new GH public key
      gh_keys:
        action: add_key
        user: leocomelli
        password: secret
        title: devel
        key: /root/.ssh/id_rsa.pub
      register: keys

    - debug:
        var: keys.stdout
